export const TODO_ADDED = 'todo/added'
export const TODO_TOGGLED = 'todo/toggled'
export const TODO_COLOR_SELECTED = 'todo/color_selected'
export const TODO_DELETED = 'todo/deleted'
export const TODO_ALL_COMPLETED = 'todo/all_completed'
export const TODO_CLEARED = 'todo/cleared'
